language: generic
dist: xenial
os:
  - linux
services:
  - docker

before_install:
  - docker build -t jmacdonald/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jmacdonald/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  region: "ca-central-1"
  app: "react-docker2"
  env: "ReactDocker2-env"
  bucket_name: "elasticbeanstalk-ca-central-1-060373546455"
  bucket_path: "react-docker2"
  on:
    branch: master

